export const data = [
  {
    id: 1,
    userName: "john_doe",
    title: "A sunny day!",
    description: "Enjoying the sunshine at the beach ☀️🌊",
    profileImg: "https://randomuser.me/api/portraits/men/1.jpg",
    postImg: "https://picsum.photos/id/1015/600/400",
    like: "120k",
    comment: "34k",
    share: "10k",
  },
  {
    id: 2,
    userName: "emma_watson",
    title: "My Morning Routine",
    description: "Start your day with a fresh smoothie! 🥤🍓",
    profileImg: "https://randomuser.me/api/portraits/women/2.jpg",
    postImg: "https://picsum.photos/id/1025/600/400",
    like: "210k",
    comment: "55k",
    share: "18k",
  },
  {
    id: 3,
    userName: "travel_with_raj",
    title: "Lost in the mountains",
    description: "Exploring the beauty of the Himalayas 🏔️",
    profileImg: "https://randomuser.me/api/portraits/men/3.jpg",
    postImg: "https://picsum.photos/id/1003/600/400",
    like: "340k",
    comment: "76k",
    share: "30k",
  },
  {
    id: 4,
    userName: "chef_sophie",
    title: "Tasty Tacos Tuesday",
    description: "Homemade tacos for the win 🌮❤️",
    profileImg: "https://randomuser.me/api/portraits/women/4.jpg",
    postImg: "https://picsum.photos/id/1080/600/400",
    like: "98k",
    comment: "22k",
    share: "5k",
  },
  {
    id: 5,
    userName: "tech_nerd",
    title: "Coding vibes",
    description: "Late night React + Tailwind coding session 😴💻",
    profileImg: "https://randomuser.me/api/portraits/men/5.jpg",
    postImg: "https://picsum.photos/id/1039/600/400",
    like: "412k",
    comment: "89k",
    share: "42k",
  },
  {
    id: 6,
    userName: "artsy_amy",
    title: "Sketching Sunday",
    description: "New art piece I'm working on 🎨🖌️",
    profileImg: "https://randomuser.me/api/portraits/women/6.jpg",
    postImg: "https://picsum.photos/id/1040/600/400",
    like: "154k",
    comment: "41k",
    share: "16k",
  },
  {
    id: 7,
    userName: "fitness_freak",
    title: "Leg Day Grind",
    description: "No pain, no gain 💪🏋️",
    profileImg: "https://randomuser.me/api/portraits/men/7.jpg",
    postImg: "https://picsum.photos/id/1021/600/400",
    like: "270k",
    comment: "60k",
    share: "20k",
  },
  {
    id: 8,
    userName: "booklover99",
    title: "Weekend reads",
    description: "Just finished this amazing book! 📚✨",
    profileImg: "https://randomuser.me/api/portraits/women/8.jpg",
    postImg: "https://picsum.photos/id/1062/600/400",
    like: "122k",
    comment: "33k",
    share: "8k",
  },
  {
    id: 9,
    userName: "gamerx",
    title: "Winning streak!",
    description: "Back-to-back wins in Valorant 😎🎮",
    profileImg: "https://randomuser.me/api/portraits/men/9.jpg",
    postImg: "https://picsum.photos/id/1069/600/400",
    like: "333k",
    comment: "77k",
    share: "25k",
  },
  {
    id: 10,
    userName: "nature_nikki",
    title: "Peaceful evening",
    description: "Sunset views in the countryside 🌄🌾",
    profileImg: "https://randomuser.me/api/portraits/women/10.jpg",
    postImg: "https://picsum.photos/id/1056/600/400",
    like: "188k",
    comment: "40k",
    share: "12k",
  },
  {
    id: 11,
    userName: "city_lights",
    title: "Night Lights",
    description: "Exploring downtown with a friend 🌆✨",
    profileImg: "https://randomuser.me/api/portraits/men/11.jpg",
    postImg: "https://picsum.photos/id/1050/600/400",
    like: "199k",
    comment: "48k",
    share: "14k",
  },
  {
    id: 12,
    userName: "petlover",
    title: "Fluffy Friday",
    description: "Cuteness overload 🐾🐶",
    profileImg: "https://randomuser.me/api/portraits/women/12.jpg",
    postImg: "https://picsum.photos/id/1049/600/400",
    like: "305k",
    comment: "70k",
    share: "22k",
  },
  {
    id: 13,
    userName: "shutterbug",
    title: "Golden hour magic",
    description: "Captured during the golden hour 📸",
    profileImg: "https://randomuser.me/api/portraits/men/13.jpg",
    postImg: "https://picsum.photos/id/1048/600/400",
    like: "412k",
    comment: "95k",
    share: "31k",
  },
  {
    id: 14,
    userName: "fashion_fiend",
    title: "OOTD 💃",
    description: "Street style goals 💅✨",
    profileImg: "https://randomuser.me/api/portraits/women/14.jpg",
    postImg: "https://picsum.photos/id/1047/600/400",
    like: "265k",
    comment: "63k",
    share: "19k",
  },
  {
    id: 15,
    userName: "car_mania",
    title: "Speed Thrill",
    description: "Ferrari 488 GTB 😍🏎️",
    profileImg: "https://randomuser.me/api/portraits/men/15.jpg",
    postImg: "https://picsum.photos/id/1046/600/400",
    like: "344k",
    comment: "59k",
    share: "17k",
  },
  {
    id: 16,
    userName: "wanderlust",
    title: "Trekking Time",
    description: "Up and down the trails 🥾🏕️",
    profileImg: "https://randomuser.me/api/portraits/women/16.jpg",
    postImg: "https://picsum.photos/id/1045/600/400",
    like: "299k",
    comment: "66k",
    share: "23k",
  },
  {
    id: 17,
    userName: "musician_max",
    title: "Sound Check",
    description: "Jamming with the crew 🎸🎤",
    profileImg: "https://randomuser.me/api/portraits/men/17.jpg",
    postImg: "https://picsum.photos/id/1044/600/400",
    like: "205k",
    comment: "50k",
    share: "14k",
  },
  {
    id: 18,
    userName: "plant_mom",
    title: "Indoor Jungle",
    description: "My plant babies are thriving 🌿🌼",
    profileImg: "https://randomuser.me/api/portraits/women/18.jpg",
    postImg: "https://picsum.photos/id/1043/600/400",
    like: "178k",
    comment: "38k",
    share: "9k",
  },
  {
    id: 19,
    userName: "movie_buff",
    title: "Retro Rewind",
    description: "Old classics never get boring 🎥🍿",
    profileImg: "https://randomuser.me/api/portraits/men/19.jpg",
    postImg: "https://picsum.photos/id/1042/600/400",
    like: "230k",
    comment: "47k",
    share: "11k",
  },
  {
    id: 20,
    userName: "soulful_sounds",
    title: "Live Vibes",
    description: "Acoustic night session 🎶🎙️",
    profileImg: "https://randomuser.me/api/portraits/women/20.jpg",
    postImg: "https://picsum.photos/id/1041/600/400",
    like: "310k",
    comment: "72k",
    share: "20k",
  },
];


export const data2 = [
  {
    id: 1,
    img: "https://picsum.photos/seed/img87809c95/600/400",
    authorImg: "https://picsum.photos/seed/author1061/100/100",
    authorName: "new_york",
    authortext: "Skyscrapers shining above bustling Times Square"
  },
  {
    id: 2,
    img: "https://picsum.photos/seed/imge20d37a5/600/400",
    authorImg: "https://picsum.photos/seed/author1271/100/100",
    authorName: "paris",
    authortext: "Eiffel Tower standing under glowing sunset"
  },
  {
    id: 3,
    img: "https://picsum.photos/seed/img62413a57/600/400",
    authorImg: "https://picsum.photos/seed/author3532/100/100",
    authorName: "tokyo",
    authortext: "Neon lights reflect over busy streets"
  },
  {
    id: 4,
    img: "https://picsum.photos/seed/img550d05ab/600/400",
    authorImg: "https://picsum.photos/seed/author4420/100/100",
    authorName: "barcelona",
    authortext: "Colorful buildings lining the Mediterranean coastline"
  },
  {
    id: 5,
    img: "https://picsum.photos/seed/img23b998b1/600/400",
    authorImg: "https://picsum.photos/seed/author1093/100/100",
    authorName: "dubai",
    authortext: "Luxury towers rise from desert sands"
  },
  {
    id: 6,
    img: "https://picsum.photos/seed/img1f49f770/600/400",
    authorImg: "https://picsum.photos/seed/author2019/100/100",
    authorName: "rome",
    authortext: "Ancient ruins scattered across charming streets"
  },
  {
    id: 7,
    img: "https://picsum.photos/seed/img1fc91e86/600/400",
    authorImg: "https://picsum.photos/seed/author4307/100/100",
    authorName: "sydney",
    authortext: "Opera House shines near the harbour bridge"
  },
  {
    id: 8,
    img: "https://picsum.photos/seed/img59ead8d1/600/400",
    authorImg: "https://picsum.photos/seed/author7839/100/100",
    authorName: "london",
    authortext: "Big Ben beside calm Thames river"
  },
  {
    id: 9,
    img: "https://picsum.photos/seed/img0ef8f876/600/400",
    authorImg: "https://picsum.photos/seed/author4049/100/100",
    authorName: "istanbul",
    authortext: "Mosques and markets blend East and West"
  },
  {
    id: 10,
    img: "https://picsum.photos/seed/img3eb8670d/600/400",
    authorImg: "https://picsum.photos/seed/author7710/100/100",
    authorName: "amsterdam",
    authortext: "Canals reflect historic Dutch architecture"
  },
  {
    id: 11,
    img: "https://picsum.photos/seed/imgee1611b6/600/400",
    authorImg: "https://picsum.photos/seed/author3455/100/100",
    authorName: "berlin",
    authortext: "Modern city shaped by rich history"
  },
  {
    id: 12,
    img: "https://picsum.photos/seed/img492379b2/600/400",
    authorImg: "https://picsum.photos/seed/author6276/100/100",
    authorName: "kyoto",
    authortext: "Cherry blossoms frame ancient wooden temples"
  },
  {
    id: 13,
    img: "https://picsum.photos/seed/img3d147c6b/600/400",
    authorImg: "https://picsum.photos/seed/author7472/100/100",
    authorName: "bangkok",
    authortext: "Golden temples glowing in humid dusk"
  },
  {
    id: 14,
    img: "https://picsum.photos/seed/img5cfd5837/600/400",
    authorImg: "https://picsum.photos/seed/author2248/100/100",
    authorName: "rio_de_janeiro",
    authortext: "Christ statue overlooks lively cityscape below"
  },
  {
    id: 15,
    img: "https://picsum.photos/seed/imgd0aa2dff/600/400",
    authorImg: "https://picsum.photos/seed/author7541/100/100",
    authorName: "los_angeles",
    authortext: "Palm trees line roads toward sunset boulevard"
  },
  {
    id: 16,
    img: "https://picsum.photos/seed/img8ebaad59/600/400",
    authorImg: "https://picsum.photos/seed/author2896/100/100",
    authorName: "mumbai",
    authortext: "Local trains rush past colorful street scenes"
  },
  {
    id: 17,
    img: "https://picsum.photos/seed/imgfd38499c/600/400",
    authorImg: "https://picsum.photos/seed/author7329/100/100",
    authorName: "seoul",
    authortext: "High-tech skyline meets ancient palace grounds"
  },
  {
    id: 18,
    img: "https://picsum.photos/seed/img260b4e59/600/400",
    authorImg: "https://picsum.photos/seed/author8603/100/100",
    authorName: "lisbon",
    authortext: "Trams roll through hilly pastel streets"
  },
  {
    id: 19,
    img: "https://picsum.photos/seed/imgf4334fdf/600/400",
    authorImg: "https://picsum.photos/seed/author5047/100/100",
    authorName: "san_francisco",
    authortext: "Golden Gate glows in morning mist"
  },
  {
    id: 20,
    img: "https://picsum.photos/seed/img607d2848/600/400",
    authorImg: "https://picsum.photos/seed/author8376/100/100",
    authorName: "venice",
    authortext: "Gondolas float under stone bridges quietly"
  }
];
